sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "4.0.0-preview.4"
  - development
  
matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix js
  - haxelib run travix node
  - haxelib run travix php
